## Resultados

pode-se ver isso executando os comandos `ls -l data | wc -l` para obter o número de páginas coletadas e `cat errors.csv | wc -l` para obter o número de páginas com erro, nas pastas das coletas correspondentes.

Para passar as tabelas para latex : https://www.tablesgenerator.com/

In [47]:
import pandas as pd
from wkdatacollector.wkio import read_json

In [8]:
info_meta = pd.DataFrame([["revision_info_2007-2009", 2846, 926, 455, 3306, -12, "sim"],
           #   ["erros_partially_revision_info_200701-200901", 926, 455, 1386, 5, "sim"],
              ["revision_info_201707-201907", 1474, 0, 1821, 3294, -1, "sim" ],
              ["revision_info_200701-200901", 2844, 930, 450, 3294, -1, "não" ],
              ["revision_info_200701-200901-errors",368,144, 82, 450, 0, "não"],
              ["revision_info_200701-200901 uniao -errors",3212,1074, 82, 3294, 0, "não"],
              ["content",0,0, 0, 0, 0, "não"],
              ["titles",40,0, 42, 82, 0, "não"],
              ["revision_info_pos_titles",34,0, 6, 40, 0, "não"],
              ["content_pos_titles",34,0, 0, 34, 0, "não"],
              ["info_and_category_200701-200901", 1589, 0, 1264, 2843, 0, "não" ],
              ["info_and_category_200701-200901+parcial", 1056, 0, 198, 1264, 0, "não" ],
              ["info_and_category_200701-200901+parcial+", 2994, -1, -1, -1, -1, "não" ],
             ], columns = ["file", "collected", "partially collected", "errors", "total", "missing", "descarted"]
            )
info_meta

file  collected  partially collected  \
0                     revision_info_2007-2009       2846                  926   
1                 revision_info_201707-201907       1474                    0   
2                 revision_info_200701-200901       2844                  930   
3          revision_info_200701-200901-errors        368                  144   
4   revision_info_200701-200901 uniao -errors       3212                 1074   
5                                     content          0                    0   
6                                      titles         40                    0   
7                    revision_info_pos_titles         34                    0   
8                          content_pos_titles         34                    0   
9             info_and_category_200701-200901       1589                    0   
10    info_and_category_200701-200901+parcial       1056                    0   
11   info_and_category_200701-200901+parcial+       2994                   -1   

    errors  total  missing descarted  
0      455   3306      -12       sim  
1     1821   3294       -1       sim  
2      450   3294       -1       não  
3       82    450        0       não  
4       82   3294        0       não  
5        0      0        0       não  
6       42     82        0       não  
7        6     40        0       não  
8        0     34        0       não  
9     1264   2843        0       não  
10     198   1264        0       não  
11      -1     -1       -1       não

## Base Original

In [16]:
hasan_ = pd.read_csv('wikipedia_dataset_hasan/wikipedia_old.csv')
hasan = set(hasan_["page_title"])
len(hasan)

3294

## Coleta de infos

1. A coleta realizada de 2009 à 2007 resultou em 1908 ou (1920) e erros (1386) (revision_info_2007-2009)
2. coleta dos artigos com erro, que tem mais rvcontinue (926) e erros (455)
3. A coleta de 2009 à 2007 resultou em 930 coletados não completamente e 450 erros

Métricas dos 3212 artigos (quantidade de revisões distintas)

In [3]:
pd.DataFrame(
    [["média", 16.353783867953908],
    ["min", 1],
    ["max", 24],
    ["std", 7.566158906605211]], columns=["métrica", "valor"]
)


métrica      valor
0   média  16.353784
1     min   1.000000
2     max  24.000000
3     std   7.566159

In [4]:
"métrica","valor"
"média",22.19838056680162
"min",1.0
"max",24.0
"std",4.061007946140082

('std', 4.061007946140082)

In [26]:
infos_and_category_1 = !ls ~/Documents/tcc-collected-data/data/info_and_category_200701-200901/data
infos_and_category = set(infos_and_category_1)

In [27]:
len(infos_and_category)


2998

In [31]:
hasan - info

3325

## Coleta de conteúdos

1,5 GB, tempo ~20000


In [68]:
base_folder = "../tcc-collected-data/data"
content_folder_1 = f"{base_folder}/content_200701-200901-errors" 
contents_1 = read_json(f"{content_folder_1}/collected-coleta1.json")["collected_pages"]
len(contents_1)

2840

In [62]:
contents_2 = read_json(f"{content_folder_1}/collected.json")["collected_pages"]
len(set(contents_2)-set(contents_1))

368

In [40]:
contents_3 = !ls ~/Documents/tcc-collected-data/data/content_info_by_id200701-200901-errors/data
cont_3 = set([x.split("|")[0] for x in contents_3])
len(cont_3)

34

In [65]:
content_table = pd.DataFrame([
           #   ["erros_partially_revision_info_200701-200901", 926, 455, 1386, 5, "sim"],
              ["1", 2840, 4, 2884,16423.973916000028 ],
              ["2", 368, 0, 368, 2360.591916999998 ],
              ["3", 34,  0, 34, 208.60236799999996 ],
              ["Total", 3242, 4, 3246 , 208.60236799999996],

             ], columns = ["coleta", "collected", "errors", "total", "tempo"]
            )
content_table

coleta  collected  errors  total         tempo
0      1       2840       4   2884  16423.973916
1      2        368       0    368   2360.591917
2      3         34       0     34    208.602368
3  Total       3242       4   3246    208.602368

# Coleta de categorias

In [74]:
infos = !ls ~/Documents/tcc-collected-data/data/info_and_category_200701-200901/data

print(len(infos))

2998


In [75]:
!ls ~/Documents/tcc-collected-data/data/info_and_category_200701-200901

collected-coleta1-salvamentototal.json	  errors-coleta1-salvamentototal.csv
collected-coleta2-salvamentoparcial.json  errors-coleta2-salvamentoparcial.csv
collected-coleta3-redirects.json	  errors-coleta3-redirecionameto.csv
collected-coleta4-byid.json		  errors-coleta4-byid.csv
collected.json				  errors.csv
data					  log.csv


In [80]:
category_folder = f"{base_folder}/info_and_category_200701-200901" 
category_1 = set(read_json(f"{category_folder}/collected-coleta1-salvamentototal.json")["collected_pages"])
category_2 = set(read_json(f"{category_folder}/collected-coleta2-salvamentoparcial.json")["collected_pages"])
category_3 = set(read_json(f"{category_folder}/collected-coleta3-redirects.json")["collected_pages"])
category_4 = set(read_json(f"{category_folder}/collected-coleta4-byid.json")["collected_pages"])
#len(set(category_1)-set(contents_1)
print(f"coleta 1 : {len(category_1)}")
print(f"coleta 2 : {len(category_2) - len(category_1)}")
print(f"coleta 3 : {len(category_3) - len(category_2)}")
print(f"coleta 4 : {len(category_4) - len(category_3)}")

coleta 1 : 1589
coleta 2 : 1057
coleta 3 : 322
coleta 4 : 31


In [90]:
#titles = open(error_file, "r").read().split('\n')[:-1]

category_err_1 = set(open(f"{category_folder}/errors-coleta1-salvamentototal.csv", "r").read().split('\n'))
category_err_2 = set(open(f"{category_folder}/errors-coleta2-salvamentoparcial.csv", "r").read().split('\n'))
category_err_3 = set(open(f"{category_folder}/errors-coleta3-redirecionameto.csv", "r").read().split('\n'))
category_err_4 = set(open(f"{category_folder}/errors-coleta4-byid.csv", "r").read().split('\n'))
#len(set(category_1)-set(contents_1)
print(f"coleta 1 : {len(category_err_1)}")
print(f"coleta 2 : {len(category_err_2)}")
print(f"coleta 3 : {len(category_err_3)}")
print(f"coleta 4 : {len(category_err_4)}")
category_err_total = len(category_err_1) + len(category_err_2) + len(category_err_3)  + len(category_err_4)
print(f"total : {category_err_total}")

coleta 1 : 1256
coleta 2 : 199
coleta 3 : 47
coleta 4 : 3
total : 1505


In [101]:
category_table = pd.DataFrame([
           #   ["erros_partially_revision_info_200701-200901", 926, 455, 1386, 5, "sim"],
              ["1", len(category_1), len(category_err_1), len(category_1)+len(category_err_1),21227.835890999966 ],
              ["2", len(category_2) - len(category_1), len(category_err_2), len(category_2) - len(category_1) + len(category_err_2), 2360.591916999998 ],
              ["3", len(category_3) - len(category_2),  len(category_err_3), len(category_3) - len(category_2) + len(category_err_3), 8187.494828000001 ],
              ["4", len(category_4) - len(category_3),  len(category_err_4), len(category_4) - len(category_3) + len(category_err_4), 8187.494828000001],
              ["Total", len(category_4), 305, 3294 , 208.60236799999996],

             ], columns = ["coleta", "collected", "errors", "total", "tempo"]
            )
category_table

coleta  collected  errors  total         tempo
0      1       1589    1256   2845  16423.973916
1      2       1057     199   1256   2360.591917
2      3        322      47    369    208.602368
3      4         31       3     34    208.602368
4  Total       2999     305   3294    208.602368

## Conversão para Html
tamanho: 2,2 GB 
tempo 12614.08667200011
~52 mil arquivos de conteúdo títulos|data

## Criação de features

In [5]:
#import pandas as pd
#data= pd.read_csv("stats.csv")
#data.hist(bins=3)
#data["distinct_revisions"].sort(data["distinct_revisions"]).value_counts()

In [6]:
#import pandas as pd
#data= pd.read_csv("stats2.csv")
#data
#data.hist(bins=3)
#data.sort_values(by=['distinct_revisions'])['distinct_revisions'].value_counts()/3212
#data["distinct_revisions"].sort(data["distinct_revisions"])value_counts()

In [7]:
def info_stats(total, titles_not_collected_completed, titles_not_colleted_even_parcially):
    #total = 3294
    #titles_not_collected_completed = 1386 # or errors from collecting completly

    #titles_not_colleted_even_parcially = 455 # or error from collecting partilly

    erros_first_collection = titles_not_collected_completed/total
    print(f"Erros na primeira coleta : {erros_first_collection}")

    erros_second_collection = titles_not_colleted_even_parcially/titles_not_collected_completed
    print(f"Erros na segunda coleta : {erros_second_collection}") 

    total_errors = (titles_not_colleted_even_parcially)/total
    print(f"Erros totais : {total_errors}") 
    collected_total = 1 - total_errors

    print(f"Coletados completamente ou parcialmente : {collected_total}") 

def info_stats_i(title):
    row = info_meta[info_meta["file"]==title]
    info_stats(row["collected"].values[0], row["partially collected"].values[0], row["errors"].values[0])
    
    
info_stats_i("revision_info_200701-200901")

Erros na primeira coleta : 0.3270042194092827
Erros na segunda coleta : 0.4838709677419355
Erros totais : 0.15822784810126583
Coletados completamente ou parcialmente : 0.8417721518987342


## Análise da primeira coleta
first_collection_folder = "../collected_data/revision_info_2007-2009"

first_collection


https://en.wikipedia.org/api/rest_v1/#/Page%20content

https://wikimedia.org/api/rest_v1/#/

https://en.wikipedia.org/w/api.php

para brincar com a API por meio de interface gráfica
https://en.wikipedia.org/wiki/Special:ApiSandbox


https://datasets.wikimedia.org/public-datasets/enwiki/article_quality/wp10-scores-enwiki-20160820.tsv.bz2

https://en.wikipedia.org/w/index.php?title=Brazil&dir=prev&action=history usar o view history

A coleta realizada de 2019 à 2014 resultou em sem tempo sleep

In [ ]:
titles_not_collect_2 = 1855
percentage = titles_not_collect_2/total
percentage

Ler sobre ORES
https://blog.wikimedia.org/2016/10/27/wikipedia-quality-trends-dataset/#cite1
https://wikiedu.org/blog/2016/09/16/visualizing-article-history-with-structural-completeness/

https://github.com/wikimedia/revscoring/blob/master/ipython/hashing_vectorizer.ipynb

Coleta realizada de 2019 à 2017

In [1]:
!ls ~/Documents/tcc-collected-data/data/content_200701-200901-errors/data

'103rd Ohio Infantry|2007-05-06T08:06:59Z'
'103rd Ohio Infantry|2007-07-16T17:28:04Z'
'103rd Ohio Infantry|2007-09-24T17:41:12Z'
'103rd Ohio Infantry|2007-11-08T23:45:07Z'
'103rd Ohio Infantry|2008-04-04T21:49:47Z'
'103rd Ohio Infantry|2008-08-10T19:48:07Z'
'103rd Ohio Infantry|2008-10-10T14:12:25Z'
'103rd Ohio Infantry|2008-11-12T23:27:10Z'
'108th United States Congress|2007-01-27T03:31:57Z'
'108th United States Congress|2007-02-26T04:51:47Z'
'108th United States Congress|2007-03-31T17:17:45Z'
'108th United States Congress|2007-04-15T17:50:01Z'
'108th United States Congress|2007-05-26T14:47:55Z'
'108th United States Congress|2007-06-29T12:31:10Z'
'108th United States Congress|2007-07-31T02:46:24Z'
'108th United States Congress|2007-09-09T12:13:34Z'
'108th United States Congress|2007-10-28T21:44:18Z'
'108th United States Congress|2007-11-29T16:45:18Z'
'108th United States Congress|2007-12-12T23:14:31Z'
'108th United States Congress|2008-01-28T05:59:59Z'
'108th United States Congress|20

'Boy Scout|2008-12-09T01:04:46Z'
'Boy Scouting (Boy Scouts of America)|2007-01-31T02:16:40Z'
'Boy Scouting (Boy Scouts of America)|2007-02-28T23:10:24Z'
'Boy Scouting (Boy Scouts of America)|2007-03-31T11:48:45Z'
'Boy Scouting (Boy Scouts of America)|2007-04-27T18:50:15Z'
'Boy Scouting (Boy Scouts of America)|2007-05-29T14:24:55Z'
'Boy Scouting (Boy Scouts of America)|2007-06-12T13:42:20Z'
'Boy Scouting (Boy Scouts of America)|2007-07-16T13:31:59Z'
'Boy Scouting (Boy Scouts of America)|2007-08-22T02:02:42Z'
'Boy Scouting (Boy Scouts of America)|2007-09-26T00:53:10Z'
'Boy Scouting (Boy Scouts of America)|2007-10-31T18:30:58Z'
'Boy Scouting (Boy Scouts of America)|2007-11-19T19:32:56Z'
'Boy Scouting (Boy Scouts of America)|2007-12-27T14:04:02Z'
'Boy Scouting (Boy Scouts of America)|2008-01-14T22:48:38Z'
'Boy Scouting (Boy Scouts of America)|2008-02-26T22:56:40Z'
'Boy Scouting (Boy Scouts of America)|2008-03-28T21:36:54Z'
'Boy Scouting (Boy Scouts of America)|2008-04-28T02:14:46Z'
'Boy Sc

'Devin Hester|2008-08-30T02:56:47Z'
'Devin Hester|2008-09-30T01:37:57Z'
'Devin Hester|2008-10-27T15:04:35Z'
'Devin Hester|2008-11-28T22:56:59Z'
'Devin Hester|2008-12-30T06:03:17Z'
'DF- 4|2008-07-09T06:28:14Z'
'DFW Tornados|2007-01-25T23:48:15Z'
'DFW Tornados|2007-02-24T16:52:38Z'
'DFW Tornados|2007-03-08T03:15:35Z'
'DFW Tornados|2007-05-28T06:55:19Z'
'DFW Tornados|2007-06-26T04:43:55Z'
'DFW Tornados|2007-07-24T17:07:08Z'
'DFW Tornados|2007-09-04T21:50:32Z'
'DFW Tornados|2007-11-18T06:23:24Z'
'DFW Tornados|2007-12-13T07:15:44Z'
'DFW Tornados|2008-01-19T01:04:17Z'
'DFW Tornados|2008-02-11T22:26:22Z'
'DFW Tornados|2008-03-30T21:51:17Z'
'DFW Tornados|2008-04-17T14:51:48Z'
'DFW Tornados|2008-05-29T03:12:56Z'
'DFW Tornados|2008-06-29T22:01:26Z'
'DFW Tornados|2008-07-30T03:58:40Z'
'DFW Tornados|2008-08-29T02:03:28Z'
'DFW Tornados|2008-09-01T09:02:01Z'
'DFW Tornados|2008-10-19T01:49:45Z'
'DFW Tornados|2008-11-08T12:57:32Z'
'DFW Tornados|2008-12-13T23:51:02Z'
'D. G. Champernowne|2007-03-04T09:0

'Jean-Baptiste Élie de Beaumont|2008-06-04T20:17:39Z'
'Jean-Baptiste Élie de Beaumont|2008-07-11T17:13:15Z'
'Jean-Baptiste Élie de Beaumont|2008-08-06T11:45:48Z'
'Jean-Baptiste Élie de Beaumont|2008-09-19T10:24:03Z'
'Jean-Baptiste Élie de Beaumont|2008-12-26T13:01:48Z'
'Jean Shepherd|2007-01-15T14:30:16Z'
'Jean Shepherd|2007-02-27T18:43:18Z'
'Jean Shepherd|2007-03-31T03:13:50Z'
'Jean Shepherd|2007-04-28T20:09:55Z'
'Jean Shepherd|2007-06-18T03:18:12Z'
'Jean Shepherd|2007-08-26T02:54:06Z'
'Jean Shepherd|2007-09-26T01:48:09Z'
'Jean Shepherd|2007-10-30T01:01:14Z'
'Jean Shepherd|2007-11-26T07:37:39Z'
'Jean Shepherd|2007-12-27T06:32:51Z'
'Jean Shepherd|2008-01-20T06:58:34Z'
'Jean Shepherd|2008-02-05T21:48:51Z'
'Jean Shepherd|2008-03-03T15:39:30Z'
'Jean Shepherd|2008-04-13T12:53:40Z'
'Jean Shepherd|2008-05-28T17:24:38Z'
'Jean Shepherd|2008-06-25T22:58:53Z'
'Jean Shepherd|2008-07-10T01:41:56Z'
'Jean Shepherd|2008-08-19T16:27:10Z'
'Jean Shepherd|2008-09-15T03:58:31Z'
'Jean Shepherd|2008-10-29T1

'Rock and alternative music in Iran|2008-11-28T04:06:53Z'
'Rock and alternative music in Iran|2008-12-22T12:07:22Z'
'Rock and Roll (dance)|2007-01-30T19:57:06Z'
'Rock and Roll (dance)|2007-02-08T20:23:51Z'
'Rock and Roll (dance)|2007-03-11T16:27:12Z'
'Rock and Roll (dance)|2007-05-30T20:53:41Z'
'Rock and Roll (dance)|2007-06-23T23:40:16Z'
'Rock and Roll (dance)|2007-07-31T23:37:11Z'
'Rock and Roll (dance)|2007-09-10T20:22:30Z'
'Rock and Roll (dance)|2007-10-29T00:39:18Z'
'Rock and Roll (dance)|2007-11-29T15:27:22Z'
'Rock and Roll (dance)|2007-12-11T14:28:05Z'
'Rock and Roll (dance)|2008-01-28T18:37:18Z'
'Rock and Roll (dance)|2008-02-03T10:14:11Z'
'Rock and Roll (dance)|2008-03-05T19:49:24Z'
'Rock and Roll (dance)|2008-04-13T20:20:42Z'
'Rock and Roll (dance)|2008-06-16T20:12:54Z'
'Rock and Roll (dance)|2008-07-03T04:53:11Z'
'Rock and Roll (dance)|2008-10-30T01:58:49Z'
'Rock and Roll (dance)|2008-11-11T22:54:02Z'
'Rock and Roll (dance)|2008-12-18T00:49:33Z'
'Rockell|2007-01-19T16:23:15Z

'West Indian cricket team in England in 1900|2007-09-18T22:49:26Z'
'West Indian cricket team in England in 1900|2007-12-02T19:49:34Z'
'West Indian cricket team in England in 1900|2008-11-02T18:32:43Z'
'West Indian cricket team in England in 1900|2008-12-14T08:02:02Z'
'West Island College|2007-02-10T01:07:12Z'
'West Island College|2007-03-24T02:44:11Z'
'West Island College|2007-04-12T22:58:13Z'
'West Island College|2007-06-25T06:29:07Z'
'West Island College|2007-08-20T22:24:06Z'
'West Island College|2007-10-25T01:13:01Z'
'West Island College|2007-11-27T21:48:56Z'
'West Island College|2008-03-31T16:19:49Z'
'West Island College|2008-04-29T03:03:01Z'
'West Island College|2008-05-20T00:35:55Z'
'West Island College|2008-06-11T02:59:27Z'
'West Island College|2008-07-28T15:34:06Z'
'West Island College|2008-11-23T20:14:13Z'
'West Island College|2008-12-12T17:24:32Z'
'West Liberty Foods|2007-01-15T01:43:48Z'
'West Liberty Foods|2007-03-27T21:14:17Z'
'West Liberty Foods|2007-05-01T19:44:04Z'
'Wes